config/routes.rb
Rails.application.routes.draw do
  get 'cart/add'
  get 'cart/remove'
  get 'cart/remove_one'

  get 'order/show'
  post 'order/create'
  resources :product
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'product#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attr.rb
class Attr < ApplicationRecord
  has_many :attribute_values
  accepts_nested_attributes_for :attribute_values, :allow_destroy => true
end

app/models/attribute_product_value.rb
class AttributeProductValue < ApplicationRecord
  belongs_to :product
  belongs_to :attribute_value
end

app/models/attribute_value.rb
class AttributeValue < ApplicationRecord
  belongs_to :attr
  has_many :attribute_product_values, dependent: :destroy
  has_many :products, through: :attribute_product_values
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/item_order.rb
class ItemOrder < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :product
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart, optional: true
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: [:new_order, :work_order, :done_order]
  has_many :item_orders, dependent: :destroy
  validates :name, presence: true,
            length: { minimum: 5 }
  validates :phone, presence: true,
            length: { minimum: 10 }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploaders :images, ImageUploader
  has_many :line_items
  has_many :item_orders
  belongs_to :category
  has_many :attribute_product_values, dependent: :destroy
  has_many :attribute_values, through: :attribute_product_values

  validates :name, presence: true,
            length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :init_cart

  def init_cart
    @cart = Cart.find(session[:cart_id])
      rescue ActiveRecord::RecordNotFound
    @cart = Cart.create
    session[:cart_id] = @cart.id
  end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def add
    @cart = init_cart
    @product = Product.find(params[:id])
    @line_item = @cart.line_items.find_by(product_id: @product)
      if @line_item
        @line_item.quantity += 1
      else
        @line_item = @cart.line_items.build(product: @product, quantity:1)
      end
      @line_item.save
    redirect_to root_path
  end


  def remove

    @cart = init_cart
    @product = Product.find(params[:id])
    @line_item = @cart.line_items.find_by(product_id: @product)
    if @line_item
      @line_item.destroy
    end
    if @cart.line_items.all.length ==0
      @cart.destroy
    end
    redirect_to root_path
  end


  def remove_one

    @cart = init_cart
    @product = Product.find(params[:id])
    @line_item = @cart.line_items.find_by(product_id: @product)
    if @line_item
      @line_item.quantity -= 1
      @line_item.save
    end
    if @line_item.quantity == 0
      @line_item.destroy
    end
    if @cart.line_items.all.length ==0
      @cart.destroy
      session[:cart_id] = nul
    end
    redirect_to root_path
  end



end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def show
    @order = Order.new
  end

  def create
    @cart = init_cart
    @order = Order.new(order_params)
    if @order.save
      @cart.line_items.each do |product|
        @line = @order.item_orders.build(product_id: product.product_id, quantity:product.quantity)
        @line.save
      end
      @cart.destroy
      #UserMailer.email_user(@order).deliver_later
      #UserMailer.email_admin(@order).deliver_later
    end
    redirect_to root_path
  end

  private
  def order_params
    params.require(:order).permit(:name, :phone, :email, :comment)
  end

end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def index
    @category_filter = params[:category_id]
    if @category_filter
      @products = Product.all.where(category_id: @category_filter)
    else
      @products = Product.all
    end

    if params[:search]
      @products=Product.where('name ILIKE ? or description ILIKE ?', "%#{params[:search]}%","%#{params[:search]}%")
    end

    @categories = Category.all.order(:position)
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  def product_params
    params.require(:product).permit(:name, :price, :description, {images: []}, :category_id, {attribute_value_ids: []})
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/concerns/cart_helper.rb
module Concerns::CartHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Интернет магазин игрушок</title>

    <% if (yield :keywords).present?  %>
        <meta name="keywords" content='<%= yield :keywords %>'/>
    <% else %>
        <meta name="keywords" content="Игрушки, купить не догого, новогоднии игрушки, купить, не дорого, интернет магазин " />
    <% end %>

    <% if (yield :description).present?  %>
        <meta name="description" content='<%= yield :description %>'/>
    <% else %>
        <meta name="description" content="Итнернет магазин игрушок, и не только" />
    <% end %>


    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


  </head>

  <body>
  <div class="container">
     <%= yield %>
  </div>
  </body>
</html>

app/views/order/show.html.erb
<h1>Работает</h1>

<%= form_with scope: :order,url:order_create_path, local: true do |form| %>

    <% if @order.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@order.errors.count, "error") %> Не коректно заполнена форма:
          </h2>
          <ul>
            <% @order.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>

    <p>
      <%= form.label :phone %><br>
      <%= form.text_field :phone %>
    </p>

    <p>
      <%= form.label :email %><br>
      <%= form.email_field :email %>
    </p>


    <p>
      <%= form.label :comment %><br>
      <%= form.text_area :comment %>
    </p>

    <table>
      <tr>
        <th width="70">Товар</th>
        <th width="50">Кво</th>
        <th width="50">Цена</th>
        <th width="100">Сумма</th>
      </tr>
      <% @all_summ = 0 %>
      <% init_cart.line_items.each do |product| %>
          <tr>
            <% @product = Product.find(product.product_id) %>
            <td><%= @product.name %></td>
            <td><%= product.quantity %></td>
            <td><%= @product.price %></td>
            <td><%= @product.price*product.quantity %></td>
            <% @all_summ += @product.price*product.quantity %>
          </tr>
      <% end %>

      <tr>
        <td></td>
        <td></td>
        <td><strong>Итого:</strong></td>
        <td><strong><%= @all_summ  %></strong></td>
      </tr>
    </table>

    <p>
      <%= form.submit %>
    </p>

    <%= link_to 'Назад', root_path %>
<% end %>

app/views/product/_order.html.erb
<% if init_cart.line_items.length > 0 %>

    <%= init_cart.id %>
    <table class="table table-sm">
      <tr>
        <th scope="col">Товар</th>
        <th scope="col">Кво</th>
        <th scope="col">Цена</th>
        <th scope="col">Сумма</th>
        <th scope="col">Действия</th>
      </tr>
      <% @all_summ = 0 %>
      <% init_cart.line_items.each do |product| %>
          <tr>
            <% @product = Product.find(product.product_id) %>
            <td><%= @product.name %></td>
            <td><%= product.quantity %></td>
            <td><%= @product.price %></td>
            <td><%= @product.price*product.quantity %></td>
            <td><%= link_to 'Добавити',cart_add_path(id: @product.id) %> <%= link_to 'Зменшити',cart_remove_one_path(id: @product.id) %> <%= link_to 'Удалить',cart_remove_path(id: @product.id) %></td>
            <% @all_summ += @product.price*product.quantity %>
          </tr>
      <% end %>

      <tr>
        <td></td>
        <td></td>
        <td><strong>Итого:</strong></td>
        <td><strong><%= @all_summ  %></strong></td>
      </tr>



    </table>
    <%= link_to 'Оформить заказ',order_show_path(id: init_cart) %>
<% end %>

app/views/product/index.html.erb
<div class="row">
  <div class="col-md-12">
    <header>
      <h1 class="text-center">Продукция:</h1>
    </header>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <h2>Категории:</h2>
    <ul class="list-group">
      <li class="list-group-item"><%= link_to "Все товары"+'('+Product.count.to_s+')', product_index_path() %></a></li>
      <% @categories.each do |category| %>
      <li class="list-group-item"><%= link_to category.name+'('+category.products.count.to_s+')', product_index_path(category_id:category) %></a></li>
      <% end %>
    </ul>

    <div class="search-box">
      <div id="sb-search" class="sb-search">
        <div>
          <%= form_tag(product_index_path, method: :get, enforce_utf8: false) do -%>
            <%= search_field_tag :search, params[:search], placeholder: "Введите название товара...", required: "", class: "sb-search-input" %>
            <span class="sb-icon-search"></span><%= submit_tag "Найти", name: nil, class: "sb-search-submit" %>
          <% end -%>
        </div>
      </div>
    </div>


  </div>
  <div class="col-md-8">
    <section class="row">
      <table class="table">
    <!--    <tr>
          <th width="70"></th>
          <th width="150"></th>
          <th width="150"></th>
          <th width="100"></th>
        </tr>
    -->
        <% @products.each do |product| %>
            <tr>
              <td width="70"><%= image_tag(product.images[0] ? product.images[0].url(:thumb) : image_url('no-image.png')) %></td>
              <td><%= product.name %></td>
              <td>Цена: <%= product.price %></td>
              <td><%= link_to 'Посмотреть', product_path(product) %></td>
              <td><%= link_to 'Купить', cart_add_path(id: product.id) %></td>
            </tr>
        <% end %>

      </table>
    </section>


  </div>
</div>






<% if init_cart %>
    <hr>

    <%= render 'order' %>

<% end %>

app/views/product/show.html.erb
<% content_for :description do %>
    <%= @product.name %> - <%= @product.description %>
<% end %>

<% content_for :keywords do %>
    <%= @product.name %>
<% end %>

<strong>Название:</strong><%= @product.name %>
<p><p>
<strong>Цена: </strong><%= @product.price %>
<p>
<strong>Описание:</strong><%= @product.description %>
<p>
  <% @product.attribute_values.each do |attr_value|%>
      <strong><%= attr_value.attr.name %> :</strong> <%= attr_value.name %><p>
  <% end %>

<p>
  <% @product.images.each do |image| %>
       <%= image_tag(image) %>
  <% end %>